theme: jekyll-theme-hacker
# Rick Sun's First CS193 Homework
- New coding experience
- Making a website
- Editing on that website
- learning new ways to code
- learning about new coding platforms
- meeting new people
